version: "3"
services:
  krakend:
    image: devopsfaith/krakend:watch
    ports:
      - 8080:8080
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
